SELECT

   ALUNOS.NOME_ALUNO AS NOME_ALUNO,

   CURSOS.CURSO AS NOME_CURSO,

   MATRICULAS.NOTA_FINAL

FROM MATRICULAS

JOIN ALUNOS ON MATRICULAS.ID_ALUNO = ALUNOS.ID_ALUNO

JOIN CURSOS ON MATRICULAS.ID_CURSO = CURSOS.ID_CURSO

ORDER BY ALUNOS.NOME_ALUNO;