
-- Desafio Final: O Aluno Destaque
SELECT
  a.NOME_ALUNO,
  ROUND(AVG(m.NOTA_FINAL), 2) AS MEDIA_NOTAS
FROM
  ALUNOS AS a
JOIN
  MATRICULAS AS m
  ON a.ID_ALUNO = m.ID_ALUNO
GROUP BY
  a.NOME_ALUNO
ORDER BY
  MEDIA_NOTAS DESC
LIMIT 1;
